title: HeroBuzz
description: Cloud + Dev + etc.
show_downloads: true

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://herobuzz.com.br" # change this to the base hostname & protocol for your site


google_analytics:

cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

encoding: utf-8
permalink: /:title/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['arquivo', 'diagramas', 'sobre', 'contato', 'newsletter']

collections:
  - diagramas

include: ["_posts", "_layouts", "_includes", "_diagramas"]
exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "gulpfile.js", "package.json", "mailchimp.html", "newsletter.html"]